<a href="https://colab.research.google.com/github/AtishaySG25/ALA-AIML/blob/main/Assignment2_ALA_(Atishay).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#1. Which patient is distant from the rest
import numpy as np

def euclidean_distance(pat_a, pat_b):
    return np.sqrt(np.sum((pat_a - pat_b)**2))

def find_distant_entries(dataset):
    num_entries = len(dataset)
    max_distance = 0
    distant_entries = None

    for i in range(num_entries):
        for j in range(i+1, num_entries):
            distance = euclidean_distance(dataset[i], dataset[j])
            if distance > max_distance:
                max_distance = distance
                distant_entries = (dataset[i], dataset[j])

    return distant_entries, max_distance

#defining the dataset
dataset = np.array([
    [76, 126, 38.0],
    [74, 120, 38.0],
    [72, 118, 37.5],
    [78, 136, 37.0]
])

#finding entry that is farthest from the rest.
distant_entries, max_distance = find_distant_entries(dataset)

print("Dataset:", dataset)
print("\nTwo most distant entries:", distant_entries)
print("Max distance:", max_distance)

Dataset: [[ 76.  126.   38. ]
 [ 74.  120.   38. ]
 [ 72.  118.   37.5]
 [ 78.  136.   37. ]]

Two most distant entries: (array([ 72. , 118. ,  37.5]), array([ 78., 136.,  37.]))
Max distance: 18.980252896102307


Using the euclidean distance we find the distance between 2 entries in the dataset. Using the 2 for loops we find the distance between a pair of points. This is assigned to the distance variable. While iterating through the loop, if we happen to find a longer distance between two pairs we update it in the max_distance variable. So this means that the pat_b is the farthest from the pat_a, which also means that it is farthest from all other entries too.

In [3]:
#2. which two patients are nearest.

import numpy as np

def euclidean_distance(pat_a, pat_b):
    return np.sqrt(np.sum((pat_a - pat_b)**2))

def find_nearest_points(dataset):
    num_points = len(dataset)
    min_distance = float('inf')
    nearest_points = None

    for i in range(num_points):
        for j in range(i+1, num_points):
            distance = euclidean_distance(dataset[i], dataset[j])
            if distance < min_distance:
                min_distance = distance
                nearest_points = (dataset[i], dataset[j])

    return nearest_points, min_distance

#dataset
dataset = np.array([
    [76, 126, 38.0],
    [74, 120, 38.0],
    [72, 118, 37.5],
    [78, 136, 37.0]
])

# Find the two nearest entries in the dataset
nearest_points, min_distance = find_nearest_points(dataset)

print("Dataset:")
print(dataset)
print("\nTwo nearest points:", nearest_points)
print("Min distance:", min_distance)


Dataset:
[[ 76.  126.   38. ]
 [ 74.  120.   38. ]
 [ 72.  118.   37.5]
 [ 78.  136.   37. ]]

Two nearest points: (array([ 74., 120.,  38.]), array([ 72. , 118. ,  37.5]))
Min distance: 2.8722813232690143


This has the same approach as finding the farthest entry. Instead of finding the farthest entry we find the entries that are nearest to each other. Alike the same approach as before we iterate using two for loops, finding distance between a pair of points and returning the pair that has the least distance between each other.

In [8]:
#3. Create a new dummy patient and then find which is the closest patient.

import numpy as np

def euclidean_distance(pat_a, pat_b):
    return np.sqrt(np.sum((pat_a - pat_b)**2))

def find_closest_entry(dataset, target_entry):
    min_distance = float('inf')
    closest_entry = None

    for entry in dataset:
        distance = euclidean_distance(entry, target_entry)
        if distance < min_distance:
            min_distance = distance
            closest_entry = entry

    return closest_entry, min_distance

# Example dataset
dataset = np.array([
    [76, 126, 38.0],
    [74, 120, 38.0],
    [72, 118, 37.5],
    [78, 136, 37.0],
])

# Given target entry
target_entry = np.array([70, 118, 39.0])

# Find the closest entry in the dataset to the target entry
closest_entry, min_distance = find_closest_entry(dataset, target_entry)

print("Dataset:")
print(dataset)
print("\nTarget Entry:", target_entry)
print("Closest Entry:", closest_entry)
print("Min Distance:", min_distance)


Dataset:
[[ 76.  126.   38. ]
 [ 74.  120.   38. ]
 [ 72.  118.   37.5]
 [ 78.  136.   37. ]]

Target Entry: [ 70. 118.  39.]
Closest Entry: [ 72.  118.   37.5]
Min Distance: 2.5


Finding the nearest data entry to dummy data entry uses the same approach as finding the nearest data entries. Here we give a random data entry and the find_closest_entry function finds the nearest data entry to that data point.

**1. What is the time complexity of this operation of finding the closest two and farthest patients? Specify using
BigO notation.**
***Answer***:
Since we will be iterating through two for loops for both the operations, the time complexity will be O(n^2), where n is the number of data entries in the dataset.

**2. Can you name one practical use of such a simple technique when about 100s of features are available and thousands of patient data is available?**
***Answer***:
This simple technique will be essential when a patient has to be treated but there is very limited time. By using the nearest point searching algorithm, we will find a patient with the similar vitals and impose their treatment method with the new patient.
We can use the farthest data points to eliminate the risk of over dosing the patient and give a reliable treatment to the patient.