**Gram Schmidt Algorithm**

In [69]:
import numpy as np

In [84]:
vectors = np.array(
    [[1,1,1], [0,0,4], [0,1,1]]
)

In [71]:
q1 = vectors[0]

In [72]:
q1_normalized = q1 / np.linalg.norm(q1)
q1_normalized

array([0., 0., 1.])

In [73]:
basis = []
basis.append(q1_normalized)
basis

[array([0., 0., 1.])]

In [74]:
q2 = vectors[1] - np.dot(q1_normalized, vectors[1])* q1_normalized
q2_normalized = q2 / np.linalg.norm(q2)
q2_normalized

array([0., 1., 0.])

In [81]:
q2 = vectors[1] - np.dot(q1_normalized, vectors[1])* q1_normalized
if np.linalg.norm(q2) < 1e-7:
    print("q2 is dependent on q1")
else:
    q2_normalized = q2 / np.linalg.norm(q2)
    basis.append(q2_normalized)
    print(q2_normalized)

[0. 1. 0.]


In [76]:
basis

[array([0., 0., 1.]), array([0., 1., 0.])]

In [77]:
q3 = vectors[2] - \
         np.dot(q1_normalized, vectors[2]) * q1_normalized - \
         np.dot(q2_normalized, vectors[2]) * q2_normalized

if np.linalg.norm(q3) < 1e-2:
    print("q3 is dependent on q1 and/or q2")
else:
    q3_normalized = q3 / np.linalg.norm(q3)
    basis.append(q3_normalized)
    print(q3_normalized)

[1. 0. 0.]


In [78]:
basis

[array([0., 0., 1.]), array([0., 1., 0.]), array([1., 0., 0.])]

In [101]:
vectors = np.array(
    [[0,0,4], [0,0,2], [1,1,1]]
)

In [104]:
def gram_schmidt(vectors):
    basis= []
    for ai in vectors:
        qnew = ai - np.sum(np.dot(ai, qj) * qj for qj in basis)  #depricated in numpy
        norm = np.linalg.norm(qnew)
        if(norm > 1e-10):
            basis.append(qnew/norm)
        else:
            raise Exception("Error")
    return np.array(basis)

In [105]:
gram_schmidt(vectors)

C:\Users\ATISHAY SG\AppData\Local\Temp\ipykernel_2076\1076716205.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  qnew = ai - np.sum(np.dot(ai, qj) * qj for qj in basis)  #depricated in numpy


Exception: Error